# Generated by Django 6.0.6 on 2026-07-16 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='task_photos/'),
        ),
    ]
