# Generated by Django 6.0.6 on 2026-07-16 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
