# Generated by Django 6.0.6 on 2026-07-19 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_detail_task_favorite_task_photo'),
        ('todo', '0002_task_photo'),
    ]

    operations = [
    ]
