# Generated by Django 6.0.6 on 2026-07-16 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_detail'),
        ('todo', '0003_task_favorite'),
    ]

    operations = [
    ]
