# Generated by Django 6.0.6 on 2026-07-19 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_merge_20260719_2047'),
        ('todo', '0004_merge_0002_task_detail_0003_task_favorite'),
    ]

    operations = [
    ]
